### ISSUE TITLE
Watching Server - java.lang.Error

### ISSUE THREAD

**Issue by Gunner76th** [Vazkii/Pillar#3]
Modpack - All The Mods 
Java on server - 1.8 update 91
OS - Ubuntu
Minecraft - 1.10.2
Forge - 12.18.0.2007
Crash Report- http://pastebin.com/TDvkXpi5

When anyone attempts to enter the End, the server crashes with the linked crash report. This has happened 3 separate times so far. Players are able to move about the Overworld and Nether with no issue, only the End appears to be affected.

**Comment by TehNut** [comment]
This should have been fixed in 5b57005ecc09e2d5b175a11fe83e1bda4321564b which was released 4 days ago.
