### ISSUE TITLE
pillar{1.1-6} crashes dedicated Forge 1.11.2 build 2201 on startup

### ISSUE THREAD

**Issue by kreezxil** [Vazkii/Pillar#6]
crash report:
https://gist.github.com/feb6e9e2f7f204d390c6b839539c112f

fml server latest:
https://gist.github.com/85caefd6dec5ca106e4135c5074888c1

**Comment by thommy101** [comment]
org.apache.commons.compress.utils.IOUtils is not available outside dev environment. 
org.apache.commons.io.IOUtils is the one you're looking for. (see MinecraftForge/MinecraftForge#5362 )

**Comment by thommy101** [comment]
There's also a wrong reference to IOUtils in src/main/java/vazkii/pillar/command/CommandPillarCopy.java
