### ISSUE TITLE
editing json prevents structure loading

### ISSUE THREAD

**Issue by StrangeThistle** [Vazkii/Pillar#7]
Pillar-1.0-5, MC 1.10.2, on a Mac using TextEdit, single player.

I'm attempting to use Pillar to add dungeon type structures to a custom skyblock pack.

If I edit the json file at all, running the pillar-reload command returns "0 structures loaded".

Before I edit the json, pillar-reload returns "1 structure loaded" and and the pillar-spawn command will place the structure.

**Comment by Insane-96** [comment]
Post the .json file

**Comment by StrangeThistle** [comment]
I don't know how I managed to break the json changing "NONE" to "SKY" last week, but with additional testing with multiple copies of the structure I only broke 1 json and was able to fix it and last weeks by copying the json that didn't break this time.

So, never mind, it really is just me being driven mad by these things.

Thank you for your time, attention, and a great mod (all your modding efforts, really, whether I choose to use them or not).

Excuse me while I head-desk a few dozen times and cry myself to sleep.

**Comment by StrangeThistle** [comment]
I did eventually identify my real problem. Even working with plain text documents, Apple's latest auto-correct features are being invasively "helpful". No, I decidedly DO NOT want smart quotes in this document!

Posted just in case anyone else is having similar issues.
